SAMPLE_IPMI_SEL_ENTRIES = [
    {
        "ID": "493",
        "Date": "Oct-06-2022",
        "Time": "19:47:13",
        "Name": "System Board ACPI_Stat",
        "Type": "System ACPI Power State",
        "State": "Nominal",
        "Event": "S0/G0",
    },
    {
        "ID": "494",
        "Date": "Oct-06-2022",
        "Time": "19:57:23",
        "Name": "System Chassis SysHealth_Stat",
        "Type": "Chassis",
        "State": "Critical",
        "Event": "transition to Non-recoverable from less severe",
    },
    {
        "ID": "495",
        "Date": "Oct-06-2022",
        "Time": "19:57:38",
        "Name": "System Board ACPI_Stat",
        "Type": "System ACPI Power State",
        "State": "Nominal",
        "Event": "S4/S5 soft-off",
    },
    {
        "ID": "496",
        "Date": "Oct-06-2022",
        "Time": "19:57:51",
        "Name": "System Board ACPI_Stat",
        "Type": "System ACPI Power State",
        "State": "Nominal",
        "Event": "S0/G0",
    },
]
SAMPLE_IPMI_SENSOR_ENTRIES = [
    {
        "ID": "0",
        "Name": "UID",
        "Type": "OEM Reserved",
        "State": "N/A",
        "Reading": "N/A",
        "Units": "N/A",
        "Event": "'OEM Event = 0001h'",
    },
    {
        "ID": "1",
        "Name": "SysHealth_Stat",
        "Type": "Chassis",
        "State": "Nominal",
        "Reading": "N/A",
        "Units": "N/A",
        "Event": "'transition to OK'",
    },
    {
        "ID": "2",
        "Name": "01-Inlet Ambient",
        "Type": "Temperature",
        "State": "Nominal",
        "Reading": "20.00",
        "Units": "C",
        "Event": "'OK'",
    },
    {
        "ID": "3",
        "Name": "Power Meter",
        "Type": "Other Units Based Sensor",
        "State": "Nominal",
        "Reading": "0.00",
        "Units": "W",
        "Event": "'OK'",
    },
    {
        "ID": "4",
        "Name": "Current meter",
        "Type": "Current",
        "State": "Nominal",
        "Reading": "22.00",
        "Units": "A",
        "Event": "'OK'",
    },
    {
        "ID": "5",
        "Name": "Fan meter",
        "Type": "Fan",
        "State": "Nominal",
        "Reading": "2200.00",
        "Units": "RPM",
        "Event": "'OK'",
    },
    {
        "ID": "6",
        "Name": "Volt Meter",
        "Type": "Other Units Based Sensor",
        "State": "Nominal",
        "Reading": "220.00",
        "Units": "V",
        "Event": "'OK'",
    },
    {
        "ID": "6",
        "Name": "Fan Meter",
        "Type": "Fan",
        "State": "Nominal",
        "Reading": "61.00",
        "Units": "%",
        "Event": "'OK'",
    },
    {
        "ID": "6",
        "Name": "Test meter",
        "Type": "Sample generic sensor",
        "State": "Nominal",
        "Reading": "54.00",
        "Units": "%",
        "Event": "'OK'",
    },
]
