name: prometheus-hardware-exporter
base: core22
adopt-info: prometheus-hardware-exporter
summary: collects hardware related information and exports them as metrics
description: |
  The prometheus-hardware-exporter is a snap for collecting hardware related
  information from the host machine, and export them as prometheus metrics.
grade: devel
confinement: strict

apps:
  prometheus-hardware-exporter:
    daemon: simple
    install-mode: disable
    restart-condition: on-abnormal
    command: bin/prometheus-hardware-exporter
    plugs:
      - network-bind

parts:
  prometheus-hardware-exporter:
    source: .
    plugin: python
    python-requirements: [./requirements.txt]
    override-build: |
      snapcraftctl build
      echo "Version: $(python3 setup.py --version)"
      snapcraftctl set-version "$(python3 setup.py --version)"
